### ISSUE TITLE
Append to the entrypoint command during run

### ISSUE THREAD

**Issue by tomsowerby** [michaelsauter/crane#105]
Hello,
This might be "undocumented" rather than an "issue", I'm a new user...

Here's what I would expect (basic untested example):

```
# crane.yml
containers:
    hello:
        dockerfile: jessie
        image: debian:jessie
        run:
            entrypoint: ["echo"]
```

Then

```
crane run hello world
```

Expected result:
fetching debian etc etc...
world

Actual result:
ERROR: No group or container matching 'world'

Is there a way to achieve what I'm trying to do?

I've been using fig in this way for npm, bower etc and it's very effective.
