### ISSUE TITLE
Bad endpoint: /tmp/docker.sock does not exists.

### ISSUE THREAD

**Issue by gregory** [michaelsauter/crane#112]
crane.yml:

``` yaml
logs:
  image: progrium/logspout
  run:
    publish: ['8000:8000']
    volumes: ['/var/run/docker.sock:/tmp/docker.sock']
    detach: true
```

docker logs container_id:

`dockergen.1 | 2014/10/22 01:36:37 Bad endpoint: /tmp/docker.sock does not exists.`

```
$docker run -it --rm -v /var/run/docker.sock:/tmp/docker.sock progrium/logspout ls /tmp/
>docker.sock
```
