### ISSUE TITLE
Typo in example crane.yaml?

### ISSUE THREAD

**Issue by dbsrv** [michaelsauter/crane#119]
In your crane example 'crane.yaml':
https://github.com/michaelsauter/crane#example

```
containers:
    apache:
        dockerfile: apache
        image: michaelsauter/apache
        run:
            volumes-from: ["crane_app"]
            publish: ["80:80"]
            link: ["crane_mysql:db", "crane_memcached:cache"]
            detach: true
```

Did you mean **app** instead of **crane_app**? Similar typo for **crane_mysql** and **crane_memcached**.

I notice you used _crane__ convention in your [crane-example](https://github.com/michaelsauter/crane-example) crane.json
