### ISSUE TITLE
Failed to execute git command in Docker container using crane

### ISSUE THREAD

**Issue by zirkome** [michaelsauter/crane#125]
I use crane to orchestrate my containers and I've got a git submodule for my project sources (a NodeJS app). When I run up my containers when it tries to `bower install` in my project root this error occurs:

```
bower jquery#~2.1.1            ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/jquery/jquery.git", exit code of #128

Additional error details:
fatal: Not a git repository: ../../.git/modules/src/web
```

Here is my `crane.yml` config file:

```
containers:
    db:
        dockerfile: images/db
        image: project/db
        run:
            detach: true
    web:
        dockerfile: images/web
        image: project/web
        run:
            volume: ["src/web:/src"]
            publish: ["8000:8000"]
            link: ["db:mongo"]
            detach: true
```

The weird thing is when I set my volume outside the current directory (`../myproject` for example) it works. But I really need to have a submodule in my repository

**Note**
- I'm on Archlinux
- Tried by hand that's work (with Docker CLI)
- I also tried with [Docker fig](https://github.com/docker/fig), It generates the same error

Thanks for your help !
