### ISSUE TITLE
CMD command not work with multiples command separated with &&?

### ISSUE THREAD

**Issue by kikicarbonell** [michaelsauter/crane#127]
I'm evaluating crane vs fig, but I have some problem with CMD configuration. For **fig** I have:

**fig.yml**

```
pg:
  image: registry.local:5000/postgres:9.1-1
  volumes:
    - ./tmp/data/pg:/var/lib/postgresql/9.1/main
  environment:
    # db postgres
    - POSTGRESQL_DB=user
    - POSTGRESQL_USER=postgres
    - POSTGRESQL_PASS=postgres
  ports:
    - "5432:5432"
redis:
  image: registry.local:5000/redis:2.8.12-1
  #volumes:
  #  - ./tmp/data/redis:/var/lib/redis
  ports:
    - "6379:6379"

mongodb:
  image: registry.local:5000/mongodb:2.4.10-1
  volumes:
    - ./tmp/data/mongodb:/data/db
  ports:
    - "27017:27017"

app:
  image: registry.local:5000/demoapp:1.0.0
  command: "/bin/bash -c 'cd /app &&
            rm -rf tmp/pids &&
            mkdir -p tmp/data/pg &&
            mkdir -p tmp/data/mongodb &&
            bundle install &&
            bundle exec rake db:create db:migrate db:seed:test &&
            rails s'"
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - pg:app_pg
    - redis:app_redis
    - mongodb:app_mongodb  
  environment: 
    - SEED=test
```

Then I build a **crane.yaml** as follow:

```
containers:
    app_postgres:
        # dockerfile: apache
        image: registry.local:5000/postgres:9.1-1
        run:
            # volumes-from: ["app"]
            publish: ["5432:5432"]
            volume: ["./tmp/data/pg:/var/lib/postgresql/9.1/main"]
            detach: true
            env: ["POSTGRESQL_DB=user", "POSTGRESQL_USER=postgres","POSTGRESQL_PASS=postgres"]
    app_app:
        image: registry.local:5000/datys/demoapp:1.0.0
        publish: ["3000:3000"]
        run:
            cmd: ["/bin/bash", "-c", "'cd /app &&
            rm -rf tmp/pids &&
            mkdir -p tmp/data/pg &&
            mkdir -p tmp/data/mongodb &&
            bundle install &&
            bundle exec rake db:create db:migrate db:seed:test &&
            rails s'"]
            interactive: true
            tty: true
            volume: [".:/app"]
            link: ["app_postgres:pg", "app_redis:redis", "app_mongodb:mongodb"]
            env: ["SEED=test"]
            detach: true            
   app_redis:
        # dockerfile: mysql
        image: registry.local:5000/redis:2.8.12-1
        publish: ["6379:6379"]
        run:
            detach: true
    app_mongodb:
        # dockerfile: memcached
        image: registry.vc.datys.cu:5000/mongodb:2.4.10-1
        publish: ["27017:27017"]
        run:
            volume: ["./tmp/data/mongodb:/data/db"]
            detach: true
```

But when I execute: `crane run` all look fine except **app_app** container:

```
NAME               IMAGE                                                    ID                      UP TO DATE      IP                PORTS  RUNNING
app_mongodb  registry.local:5000/mongodb:2.4.10-1    fc21d3196e5a    true       10.1.1.200 27017/tcp,28017/tcp,    true
app_postgres registry.local:5000/postgres:9.1-1            5f8a5d862797    true            10.1.1
.201    5432/tcp,               true
app_redis    registry.local:5000/redis:2.8.12-1                e5e0a97baecb    true            10.1.1
.202    6379/tcp,               true
app_app      registry.local:5000/datys/demoapp:1.0.0                                true            -
        -                       false

```

And I don't know how get output of previous execution of app_app containers.
