### ISSUE TITLE
Host run hooks for pre-cmd, post-cmd etc.

### ISSUE THREAD

**Issue by dreamcat4** [michaelsauter/crane#148]
It would be great to have some way to add host-side commands to run before `crane lift` `crane provision` etc. And post hooks too.

This allows us to continue using Crane CLI interactively during development, without wrapping the `crane` cmd in some other custom, archaic or cumbersome script.

There are many uses. Pretty much anything else that can't be run in a container, which must be run on the host side.

For example:

* To run pipework and add network interfaces to containers when they are started.
* To run a command to check that a service has come up successfully after crane lift.
* To do something (like push or publish new images, tweet them), after crane provision.

Guess it could be another key in the `crane.yml` or something. Haven't thought about it very much. 

For one thing, it would be necessary to decide whether it is worthwhile to differentiate between global, per-group, and per-container pre/post hooks. And which specific set of actions (provision, start, etc) need to have hooks.

**Comment by bjaglin** [comment]
Related discussion in https://github.com/michaelsauter/crane/pull/144

**Comment by michaelsauter** [comment]
I think this is a good idea, and would like to see this happen but have no time atm. I reckon the right level would be per-container (at least to start out with). @bjaglin Upon reading your initial proposal again, I like it. I'll have a look at this when I get to it, or, since this could take a while, someone can beat me to it :)

**Comment by michaelsauter** [comment]
Further to the proposal, I'm thinking the best hook points are probably `create`, `start`, `stop` and `remove` (and for each, a possible `pre` and `post` hook).

**Comment by bjaglin** [comment]
@michaelsauter something like that?
```
containers:
  foo
    image: foo
    hooks:
      create:
        pre: echo create...
        post: echo create done!\n
      start:
        pre: echo start...
        post: echo start done!\n
      stop:
        pre: echo stop...
        post: echo stop done!\n
      remove:
        pre: echo remove...
        post: echo remove done!\n
```

Each command being run interactively as a shell command (do we really need the clunky, array-based, exec-syntax?) for which the return status will be checked (allowing the process to be interrupted if a condition is not fullfilled, which was the original goal of #74).

**Comment by michaelsauter** [comment]
@bjaglin Yes. Wondering whether we should move `hooks` to the top level next to `containers` and `groups`? The name of the container could then be either on the level above `create`, `start` etc., or below. Not sure what's best there.

**Comment by bjaglin** [comment]
I'd say that if we go for per-container hooks, I'd rather have the hooks declaration together with the rest of my container declaration as above rather than in anoter top-level field - easier to follow and less prone to container names spelling errors IMHO.

**Comment by dreamcat4** [comment]
Pity then that groups are simple arrays. As would be nice to specify hooks on not just individual containers, but also on a group of them. e.g. `dev`, `prod`, `test` groups etc.

For syntax I would suggest a slight modification. Learning from a similar mechanism in Freebsd ports. Since most times people need either a pre- or a post- hook. But not very often both of them at once. And that when multiple selections occur, those selections are sparse, not following any pre-structered pattern.

So rather than this guys:

```
    hooks:
      create:
        pre: echo create...
        post: echo create done!\n
      start:
        pre: echo start...
        post: echo start done!\n
      stop:
        pre: echo stop...
        post: echo stop done!\n
      remove:
        pre: echo remove...
        post: echo remove done!\n
```

What about this instead:

```
      hooks:
        pre-create: echo create...
        post-create: echo create done!\n
        pre-start: echo start...
        post-start: echo start done!\n
        pre-stop: echo stop...
        post-stop: echo stop done!\n
        pre-remove: echo remove...
        post-remove: echo remove done!\n
```

Which is nearly same thing, but slightly more compact. In real-world usage it look better as not all possible hooks are used on same container. e.g.

```
      hooks:
        pre-create: echo create...
        post-remove: echo remove done!\n
```

**Comment by bjaglin** [comment]
+1 for the flatter structure. As for supporting hooks for other things than container, we could explore @michaelsauter 's idea to have a top-level `hooks` field (which I initially -1'ed because I was focusing on per-container), in which case keys could be either container or group references.

**Comment by dreamcat4** [comment]
Hmm. Just thinking out loud here, as if the existing system had not been as such:

```
containers:
  c1:
  c2:

# current way
default: [ c1, c2 ]
group2: [ c1, c2 ]
group3: [ c1, c2 ]

# new way
group(s):
  default:
    containers: [ c1, c2 ]
    hooks:    
  dev:
    container(s): [ c1, c2 ]
    hooks:
  prod:
    container(s): [ c1, c2 ]
    hooks:

```

Above ^^ can is possible if we merely assert that no crane group can have the name `group` or `groups`. Then the existing(previous) top-level way stills also remains a valid syntax. Not breaking backwards-compatibility.

I think having a `groups` top-level key is better than having a `hooks` top-level key. For future expansion of other possible new features and other stuff to do with groups. e.g. dependency management, including groups inside other groups ("super-groups"), etc.

**Comment by bjaglin** [comment]
I am not sure I follow, as `groups` already exists - your previous example (for the current way) should be
```
containers:
  c1:
  c2:
groups:
  default: [ c1, c2 ]
  group2: [ c1, c2 ]
  group3: [ c1, c2 ]
```

Therefore your proposal would require supporting different types under `groups/<groupname>`: array for backward compatibility, and map for the suggested `{containers,hooks}` map.

My proposal above in an example:
```
containers:
  c1:
  c2:
groups:
  default: [ c1, c2 ]
  group2: [ c1, c2 ]
  group3: [ c1, c2 ]
hooks:
  c1:
    pre-create: echo creating c1...
  group2:
    post-stop: echo group2 container stopped!\n
  default:
    pre-start: echo start...
    post-start: echo start done!\n
```
