### ISSUE TITLE
Container arguments

### ISSUE THREAD

**Issue by zajca** [michaelsauter/crane#157]
I'm using docker-gen container to build config for nginx like this:
```
docker run --volumes-from proxy \
    -v /var/run/docker.sock:/tmp/docker.sock \
    -v /etc/docker-gen/templates:/etc/docker-gen/templates \
    --name proxy-gen\
    -d jwilder/docker-gen -notify-sighup nginx -watch -only-published=false /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
```
this should by equivalent in crane but I'm missing something. My guess is arguments are somehow wrong. Also sometimes when I'm using non-trusted repositories I don't know what is executable name and I need just pass arguments not rewrite cmd. Or I'm wrong?
```
proxy-gen:
    image: "jwilder/docker-gen"
    run:
      detach: true
      volumes-from: ["proxy"]
      volume:
        - "/var/run/docker.sock:/tmp/docker.sock"
        - "/etc/docker-gen/templates:/etc/docker-gen/templates"
      cmd:
        - "/usr/local/bin/docker-gen -notify-sighup nginx -watch -only-published=false /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
```

**Comment by bjaglin** [comment]
your `cmd` is currently an array with an item - i am guessing you want an array with several items, or a string. Either of these should work:
```
proxy-gen:
    image: "jwilder/docker-gen"
    run:
      detach: true
      volumes-from: ["proxy"]
      volume:
        - "/var/run/docker.sock:/tmp/docker.sock"
        - "/etc/docker-gen/templates:/etc/docker-gen/templates"
      cmd: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-published=false /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
```
```
proxy-gen:
    image: "jwilder/docker-gen"
    run:
      detach: true
      volumes-from: ["proxy"]
      volume:
        - "/var/run/docker.sock:/tmp/docker.sock"
        - "/etc/docker-gen/templates:/etc/docker-gen/templates"
      cmd:
        - /usr/local/bin/docker-gen
        - -notify-sighup 
        - nginx
        - -watch
        - -only-published=false
        - /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
```
And by the way, double quotes are not necessary for string values in YAML.

**Comment by zajca** [comment]
nice I miss that I'm defining array

this is working just fine, thanks @bjaglin 
```
containers:
  proxy-gen:
    image: "jwilder/docker-gen"
    run:
      detach: true
      volumes-from: ["proxy"]
      volume:
        - "/var/run/docker.sock:/tmp/docker.sock"
        - "/etc/docker-gen/templates:/etc/docker-gen/templates"
      cmd:
        - -notify-sighup
        - nginx
        - -watch
        - -only-published=false
        - /etc/docker-gen/templates/nginx.tmpl
        - /etc/nginx/conf.d/default.conf
```
