### ISSUE TITLE
Error with dependencies when lifting a specific container

### ISSUE THREAD

**Issue by adrianhurt** [michaelsauter/crane#161]
Hi, I'm new to Crane and I don't know if I'm missing something or it's a bug, but having this config file:

```
containers:
  mysql-storage:
    image: ubuntu:14.04
    run:
      volume: ["/var/lib/mysql"]
      detach: true
  mysql:
    image: mysql
    run:
      volumes-from: ["mysql-storage"]
      publish: ["3306"]
      env:
        - MYSQL_ROOT_PASSWORD=rootpass
        - MYSQL_DATABASE=test
      detach: true
  mysql-backup:
    image: mysql-backup
    dockerfile: mysql-backup
    run:
      link: ["mysql:mysql"]
      volume: ["/mysql/backups:/mysql/backups"]
      env:
        - MYSQL_USER=root
        - MYSQL_PASSWORD=rootpass
        - MYSQL_DATABASE=test
      detach: true

groups:
  mysql-group: ["mysql-storage", "mysql", "mysql-backup"]
```

When I run `crane lift` or `crane lift mysql-group` everything works perfectly, but it doesn't directly through the containers with `crane lift mysql-backup` nor `crane lift mysql`. I get the error:
```
ERROR: Dependencies for container(s) mysql-backup could not be resolved. Check for cyclic or missing dependencies, or use -d/--cascade-dependencies to automatically attempt to recursively include dependencies in the set of targeted containers.
```

**Comment by bjaglin** [comment]
If you explicitly specify a target (without cascading flags), crane will prevent you from running a command if dependencies are not honored. It's a feature, as well as the [cascading flags](https://github.com/michaelsauter/crane/blob/v1.1.1/README.md#advanced-usage) allowing to implicitly target other containers. What do you expect from `crane lift mysql-backup` if `mysql` doesn't exist?

**Comment by adrianhurt** [comment]
I've just re-read the readme and I've seen the flag `--cascade-dependencies`. With it as `all` it works, and I see that the `crane lift` help suggest that this flag is `none` as default. So maybe it has `none` as default while targeting containers and `all` for the rest. It's a bit confusing.

**Comment by bjaglin** [comment]
Cascading is always disabled by default. `crane lift`, `crane lift mysql-group` and `crane lift mysql-backup --cascade-dependencies all` are all equivalent - they apply the lift command to 3 containers. In the first two cases you just used aliases (no target = all containers, a group = all containers in that group).

**Comment by adrianhurt** [comment]
Wow, you're very fast answering! Thanks for that! I see the point… so as I understand, in your two first cases, it's targeting to multiple containers, so it simply lift them (I suppose at the correct order checking their dependencies?)

**Comment by bjaglin** [comment]
Right, dependency management allows to order explicitly targeted containers according to the dependency graph so order on the CLI or in the container/group definition doesn't matter. Cascading is related but an extension of that since it allows you to traverse the graph (in one way or another) to include more containers, which will also be ordered properly.

**Comment by adrianhurt** [comment]
Thanks, it's totally clear now. By the way, talking about dependency management..., is there any option to declare a dependency to another container, or maybe from a group to another, or even a priority for non-dependent containers or groups to get lifted one before other, but without using `volumes-from` nor `links`? I think I can be more clear with an example. Suppose I have two groups of containers and they are independent: a web-service (mysql and webapp) and a log-service (fluentd and elasticsearch). The fluentd container uses a discovering service to get the logs of every container without the need of any link.

```
containers:
  mysql:
    image: mysql
    run:
      …
  web:
    image: my-web-image
    run:
      link: ["mysql:mysql"]
      ...

  elasticsearch:
    image: michaloo/elasticsearch
    run:
      ...
  fluentd:
    image: michaloo/fluentd
    run:
      link: ["elasticsearch:elasticsearch"]
      ...

groups:
  web-service: ["mysql", "web"]
  log-service: ["elasticsearch", "fluentd"]
```

I could lift them with simply `crane lift` and every container will be started. But is there any option to indicate a priority or maybe create a kind of dependency between the groups to get that the log-service is always started before the web-service in order to catch every log of the web-service from the very beginning?

**Comment by bjaglin** [comment]
Glad I could explain. PRs are welcome if you found the README unclear :)

Regarding materializing dependencies without the use of docker relationships (there is also `net=container:foo` by the way), I am afraid there is no support for that at the moment and AFAIK is not on the roadmap. I am personnally just introducing fake `volumes-from` dependencies if I want ordering.

For the record, explicit ordering was planned for 0.9.0 as a specific configuration field but reverted before the release, mostly because of the complexity and the lack of specified use-cases (https://github.com/michaelsauter/crane/commit/2ab832cb89a82e27c480a0ebc438cf95edc5e341).

**Comment by adrianhurt** [comment]
Ok, I suppose that simply with the command `crane lift log-service web-service` would be enough (and if not with two different commands). Thanks

Another example of dependency apart from `link`, `volumes-from` and `net`. I have basically 3 containers: mysql, mysql-backup and web. In my case, I use mysql-backup also to import the last found backup or an initial one. So, when mysql-backup starts, it waits until mysql is ready to use (with a loop and checking manually the mysql connection) and when it's ready it imports an initial database with the needed structure. On the other hand, when the web container starts, it also has to wait until the database is ready. But not only that the mysql service is ready, also that the database has been imported by the mysql-backup container.
```
containers:
  mysql:
    run:
      ...
  mysql-backup:
    run:
      link: ["mysql:mysql"]
      volume: ["/mysql/backups:/mysql/backups"]
      ...
  web:
    run:
      link: ["mysql:mysql"]
      …
```
As you can see in the config file, the web container has only a link to mysql (obviously), but it needs also another dependency to mysql-backup because if it is started without mysql-backup it will never starts. It's true that I could use fake `volumes-from`, but then I would have a real volume in web from the mysql-backup, and well… it could be a work-around but conceptually… I don't know nothing about go, I've tried to see the file `dependencies.go` but I don't dare try to make some PR, but maybe the inclusion of a new type of dependency that do nothing more than declare it would be interesting. For example:
```
  web:
    run:
      link: ["mysql:mysql"]
      dependency: ["mysql-backup"]
      …
```
Or maybe simply `dep`.

By the way, that's also the reason I would like to have the `hook` option available. Now I need that mysql-backup and web containers wait for the readiness of the database and it is done within the container execution. But I think it would be better doing that even before to start the containers. So a `pre-start` would let me to check if the service is ready or not (with a timeout) and logging that if necessary, and only start the container if everything is correct.
