### ISSUE TITLE
Define variables within crane.yml

### ISSUE THREAD

**Issue by adrianhurt** [michaelsauter/crane#163]
I know you can use variables within a `crane.yml` directly as it was a shell script using `$` character. But it implies you have to declare them previously apart from the file. I think it could be interesting to have the chance to declare them also directly within the file. Then the deployment would be more portable. An example could be:
```
variables:
  - db_user=root
  - db_password=rootpass
  - db_database=my_database

containers:
  mysql:
    run:
      env:
        - MYSQL_ROOT_PASSWORD=@db_password
        - MYSQL_DATABASE= @db_database
  mysql-backup:
    run:
      link: "mysql:mysql"
      volume: ["/mysql/backups:/mysql/backups"]
      env:
        - MYSQL_USER=@db_user
        - MYSQL_PASSWORD=@db_password
        - MYSQL_DATABASE=@db_database
  web:
    run:
      link: ["mysql:mysql"]
      env:
        - MYSQL_USER=@db_user
        - MYSQL_PASSWORD=@db_password
        - MYSQL_DATABASE=@db_database
```
Another possibility could be using directly the `$` character and parse each variable and export it directly within the scope.

I really would like to help more and uploading the corresponding PR, but I don't have enough time now to start with Go language…

Thanks again for the project!

**Comment by bjaglin** [comment]
You can do something very similar just by using a YAML feature: http://yaml.org/type/merge.html

**Comment by adrianhurt** [comment]
Cool!, I didn't know the alias and merging features of YAML. As I see you can do this:
```
aliases:
  - &db_user MYSQL_USER=root
  - &db_password MYSQL_PASSWORD=rootpass
  - &db_database MYSQL_DATABASE=my_database

containers:
  web:
    run:
      link: ["mysql:mysql"]
      env:
        - *db_user
        - *db_password
        - *db_database
```

However it implies that every key in the corresponding `key=value` string should be the same. I was trying to make more with this features but it seems the fact of using a string array for `env` stops us. I know it's a direct mapping to `-e` parameter of Docker, but if we could also declare the `env` as a mapping (and covert it finally into a `key=value` string, we could do some interesting things as the following examples.
```
aliases:
  - &db_user root
  - &db_password rootpass
  - &db_database my_database

containers:
  mysql:
    run:
      env:
        MYSQL_ROOT_PASSWORD: *db_password
        MYSQL_DATABASE: *db_database
  web:
    run:
      link: ["mysql:mysql"]
      env:
        MYSQL_USER: *db_user
        MYSQL_PASSWORD: *db_password
        MYSQL_DATABASE: *db_database
```

Or even define a block and override some environment variable:
```
aliases:
  - &db_user root
  - &db_password rootpass
  - &db_database my_database
  - &db_env
    MYSQL_USER: *db_user
    MYSQL_PASSWORD: *db_password
    MYSQL_DATABASE: *db_database
    LOG: true

containers:
  web:
    run:
      link: ["mysql:mysql"]
      env: *db_env
  web-test:
    run:
      link: ["mysql:mysql"]
      env:
        <<: *db_env
        MYSQL_DATABASE: test
        LOG: false
```
You could even merge multiple blocks within the same `env`. It could behave as a kind of mixin.
