### ISSUE TITLE
Extra dependencies for Dependency-Management

### ISSUE THREAD

**Issue by adrianhurt** [michaelsauter/crane#170]
Now there are 3 different kinds of dependencies between containers: `link`, `volumes-from` and `net`. They allow crane to know the order it has to lift multiple containers. These 3 kind of dependencies correspond with the docker ones. In docker, they declare not only a dependency but also the way each container is affected by the other. However, when you try to manage multiple containers with crane, there are some situations where you need to establish an extra dependency without any other implication between them. I think a way to declare this extra dependency would allow us to tell crane that it has to lift the containers in a specific order.

# Automated Nginx
Imagine a nginx container that configures itself watching the containers instead of linking them manually ([jwilder/nginx-proxy](https://registry.hub.docker.com/u/jwilder/nginx-proxy/) is a good example). Then there's no need to define any `link` between each web container and nginx one. However, it's obvious there's a dependency between them. Each web container __needs__ the nginx to work. One possible way to declare this could be:
```
containers:
  web1:
    run: …
    needs: ["nginx"]
  web2:
    run: …
    needs: ["nginx"]

  nginx:
    image: jwilder/nginx-proxy
    run:
      publish: ["80:80"]
      …
```
Then, you can lift for example `web1` with `crane lift --cascade-dependencies=all web1`. Of course, you could solve this adding a group for each combination `webN-nginx` and lift the group, but I think it's interesting to declare this kind of dependency within the container's declaration.

# Restoring a Mysql backup
For example, imagine 3 containers: `db`, `db-restore-and-backup` and `web`. The container `db-restore-and-backup` needs to be started after `db` and it checks the content of the database. If there is no data, it restore the last backup it has. And of course it is in charge of backup the database everyday as well. 
```
containers:
  db:
    run:
      ...
  db-restore-and-backup:
    run:
      link: ["db:db"]
      volume: ["/db/backups:/db/backups"]
      ...
  web:
    run:
      link: ["db:db"]
      …
```
Then the `web` container needs to access to the database so we declare it with a `link: ["db:db"]`. However, when the containers are lifted the first time, the database is empty. It implies that `web` container should be started not only after `db` but also after `db-restore-and-backup`. I know there are different ways to solve that:
* Using sleeps... no way.
* Using extra "waiter" containers that uses `volumes-from` to workaround this issue. It lets you to define correctly the order of lifting each container, but I think adding extra containers and fake `volumes-from` declarations is not a very elegant way to solve this.
* Using active waiting loops to check when the database is ready to use. This needs to be done within the execution of the `web` container before starting the app. Well, I'm doing that now but I think it isn't as elegant as we could desire. Firstly, you must also define this extra dependency with fake `volumes-from` or using group declarations (I need to be sure `db-restore-and-backup` is always executed with `web`).

For that reasons, I think that the ability of declaring this extra dependency with the addition of the [support of container hooks feature](https://github.com/michaelsauter/crane/pull/159) would be the perfect solution for this kind of things. It could be resolve with something like this:
```
containers:
  db:
    ...
  db-restore-and-backup:
    ...
  web:
    run:
      link: ["db:db"]
      …
    needs: ["db-restore-and-backup"]

hooks:
  db-restore-and-backup:
    pre-start: for i in `seq 1 10`; do sleep 1 && docker exec db mysql -u root -prootpass database -e "show tables" && exit 0 || echo retrying...; done; exit 1
  web:
    pre-start:  for i in `seq 1 10`; do sleep 1 && docker exec db mysql -u root -prootpass database -e "describe one_of_my_tables" && exit 0 || echo retrying...; done; exit 1
```
With this, I'm sure that the order of execution will be `db` -> `db-restore-and-backup` -> `web`. And also that `db-restore-and-backup` will be started when the database is ready to use, and `web` when it has also the data initialized correctly, not before.

# Other options
Another alternative could be the use of `wait-for` and `wait-until`.
For the nginx example, we could use `wait-for`:
```
containers:
  web1:
    run: …
    wait-for: ["nginx"]
  web2:
    run: …
    wait-for: ["nginx"]

  nginx:
    image: jwilder/nginx-proxy
    run:
      publish: ["80:80"]
      …
```
And for the mysql example, we could use `wait-until`:
```
containers:
  db:
    ...
  db-restore-and-backup:
    run:
      link: ["db:db"]
      …
    wait-until:
      db: mysql -u root -prootpass database -e "show tables"
  web:
    run:
      link: ["db:db"]
      …
    wait-for: ["db-restore-and-backup"]
    wait-until:
      db: mysql -u root -prootpass database -e "describe one_of_my_tables"
```
Where `wait-until` would wait until the specified command would return a _0 status_ (with an active waiting loop and `docker exec` functionality).

**Comment by adrianhurt** [comment]
# Another option
Other possibility could be ability for each container to define a way to know if it's ready.
```
containers:
  db:
    …
    ready-when: mysql -u root -prootpass database -e "show tables"
  db-restore-and-backup:
    run:
      link: ["db:db"]
      …
    wait-for: ["db"]
    ready-when: mysql -u root -prootpass database -e "describe one_of_my_tables"
  web:
    run:
      link: ["db:db"]
      …
    wait-for: ["db-restore-and-backup"]
    ready-when: curl localhost:9000 | grep '<h1>Home</h1>'
```
Where the command defined by `ready-when` is executed by crane using `docker exec`, and the `wait-for` would wait until the corresponding `ready-when` of the target container is satisfied.

These are only options fore new features. But I think it could enhance crane functionality.

**Comment by adrianhurt** [comment]
I've decided to split this issue in two. I've just opened another one (#171) to discuss about the ability to declare the readiness of a container. And this issue is only to discuss the ability to add an extra dependency. So then you can ignore the `wait-for` and `wait-until` examples. Let's focus only in that extra dependency `needs` (or other name, of course).

**Comment by dreamcat4** [comment]
+1 For any way to implement this feature (user-controlled dependancies). Rather than fallback to Alphabetical (the current).

P.S. A simple hack until then is to prefix your container names with `a,b,c,d,e,f,g,…etc` to force the startup order. E.g.

```yaml
containers:
  a_my_dependant_service_1:
    image: elasticsearch
  b_my_dependant_service_2:
    image: mysql
  c_my_web_application:
    image: rails/rails
```

Then your containers will always fail over to starting in the order `a,b,c`. Sorry it's an undocumented hack though. It would be better to make as a proper feature ~ I have no objection to your proposal to use `needs:` key however there may be other suitable key names, e.g. `depends:` comes to mind as an obvious one.

Writing `needs:` suggests general and multiple possible types (kinds) of dependancy. e.g. including not just other containers to start up. Wheras `depends:` is un-ambiguous to containers. My other caveat (in other issue #171) also stands here too:

We might as well be thorough about it and check if some similar feature is already in the works for the official docker project. Before taking that name. To avoid possible future conflicts / duplication / and confusion over official docker features.
