### ISSUE TITLE
include other config files and merge them together.

### ISSUE THREAD

**Issue by gregory** [michaelsauter/crane#175]
Would be great to get a feature where we could include another yml file: 

```yml
#db.yml
containers:
    mysql:
        image: mysql
        run:
            env: ["MYSQL_ROOT_PASSWORD=mysecretpassword"]
            detach: true
    memcached:
        image: tutum/memcached
        run:
            detach: true
```

```yml
#crane.yml
include: 
  - ./db.yml
containers:
    apache:
        image: some-apache-image:latest
        run:
            volumes-from: ["app"]
            publish: ["80:80"]
            link: ["mysql:db", "memcached:cache"]
            detach: true
    app:
        dockerfile: app
        image: michaelsauter/app
        run:
            volume: ["app/www:/srv/www:rw"]
            detach: true
```

including db would have the keys from crane.yml merged over the ones of db.yml

In our case, we have couple services with a lot of env variables and the crane file starts to be pretty big...
