### ISSUE TITLE
Support for multiple link aliases

### ISSUE THREAD

**Issue by mishak87** [michaelsauter/crane#177]
It would be nice to support [multiple links of single container](https://github.com/docker/docker-py/pull/153).

It is useful ie. for application that has several databases but for dev it is simpler to use just one.
db1.host db2.host, db1-ro.host etc. (example taken from legacy app)

Defining more aliases results in `ERROR: runtime error: slice bounds out of range`.
```yaml
containers:
    a:
        run:
            link:
                - db:db1.host
                - db:db2.host
                - db:db1-ro.host
```
