### ISSUE TITLE
Docker 1.6 and Crane

### ISSUE THREAD

**Issue by b0c1** [michaelsauter/crane#183]
Hi guys, 
I tried to start es container with new installed docker 1.6 but I can't, the relevant crane.yml:
```yml
containers:
    es:
        image: library/elasticsearch
        run:
            hostname: es.finesolution.hu
            publish: ["9200:9200","9300:9300"]
            detach: true
```

The result:
```
root@work:/opt/docker# crane lift es
Pulling image library/elasticsearch ... latest: Pulling from elasticsearch
9faf01c9b0ef: Already exists
61e9c91c4f08: Already exists
98bfb082a4df: Already exists
bd49bdbfa04d: Already exists
3e45d99a86e3: Already exists
42035c05fd86: Already exists
356283e075b4: Already exists
8033098e546c: Already exists
edf7759c72db: Already exists
db8adcee253a: Already exists
cf7b4a042d78: Already exists
a5ac1111b400: Already exists
b0f6e5fffc85: Already exists
218a0f35a79f: Already exists
b07ccf221d14: Already exists
6754f65d7dc6: Already exists
3e91ed95f745: Already exists
ddbe3399d0e2: Already exists
05187f993ce8: Already exists
8a7f9478dbd4: Already exists
5f82d867a994: Already exists
Digest: sha256:1c6635154be8ab07e85e98d2272c2dee98a43f1416ab6dca32bdf443df8c3a9b
Status: Image is up to date for elasticsearch:latest
Starting container es ... Error response from daemon: Cannot start container es: Error getting container 974dcd23a69e9b7b3c8cb67b52abbdfa1a50c3598eddab0e15d72d40a2b0f20d from driver aufs: error creating aufs mount to /var/lib/docker/aufs/mnt/974dcd23a69e9b7b3c8cb67b52abbdfa1a50c3598eddab0e15d72d40a2b0f20d: invalid argument
FATA[0000] Error: failed to start one or more containers
ERROR: exit status 1

```
