### ISSUE TITLE
ignore :ro and :rw keywords in volumes-from when calculating deps

### ISSUE THREAD

**Issue by cu** [michaelsauter/crane#188]
In some of my containers, I append the ":ro" keyword to the end of the "volumes-from" value to indicate to docker that the volumes should be mounted read-only. Unfortunately, it looks like crane uses the whole string when calculating dependencies and throws an error when it doesn't see another container named "foo:ro", even though foo is already defined.

Example crane.yaml:
```
containers:
    foo_data:
        image: data-volume
        run:
            detach: true
            volume: ["/var/lib/foo"]
            cmd: ["true"]
    foo_backup:
        image: data-volume
        run:
            detach: true
            volumes-from: ["foo_data:ro"]
            publish: ["222:22"]
```
The error shown:
```
ERROR: Dependencies for container(s) jenkins_backup could not be resolved. Check for cyclic or missing dependencies, or use -d/--cascade-dependencies to automatically attempt to recursively include dependencies in the set of targeted containers.
```
