### ISSUE TITLE
support for hooks inside the container

### ISSUE THREAD

**Issue by missedone** [michaelsauter/crane#193]
Hi
in our case, when we start our dev env, we want to copy some sql data from host to container, and execute the seeding script to inject the data into database inside the container.

as for now the hooks are being running on the host, so i suggest to add sort of 'inner-hooks' at the top-level of the configurations, for example:

```
...
inner-hooks:
  # scripts run once the container started
  post-start: xxx
  # script run before the container stopped
  pre-stop: yyy
```

i know it's workaround with current hooks mechanism, like below:

hooks:
  post-start: docker exec ~~-rm~~ -it <container_id> <script_to_be_executed>

but i think with 'inner-hooks' it look more clear, what do you think?
thanks
