### ISSUE TITLE
Hooks exposed envars

### ISSUE THREAD

**Issue by marconi** [michaelsauter/crane#204]
I have a use-case wherein the container requires envars to be passed, but the values for these envars aren't hardcoded, they are being retrieved from `consul`. 

How can I make it such that `pre-start` hook will `export` these envars and when crane starts these envars becomes available across my `crane.yml` file?

Here's what I have:

```
es-postgres:
    image: ubuntu:14.04
    env: ["POSTGRES_USER", "POSTGRES_PASSWORD"]
    cmd: echo "$POSTGRES_USER:$POSTGRES_PASSWORD"

hooks:
  es-postgres:
    pre-start: bash -c "source ./bin/postgres && setup_postgres"
```

wherein `setup_postgres` is:

```
setup_postgres() {
  export POSTGRES_USER=$(consul_kv_get 'postgres/user')
  export POSTGRES_PASSWORD=$(consul_kv_get 'postgres/password')
}
```

I think this is because my `pre-start` runs the command on a separate process that's running `crane.yml` and so the envars are exposed there. I want it to be available at `crane.yml`.
