### ISSUE TITLE
Starting containers in parallel?

### ISSUE THREAD

**Issue by jleskovar** [michaelsauter/crane#211]
Hi there,

Sorry if this is a silly question, but is there a way to have containers -- that are completely indepedently of one another -- to start up in parallel? From the quick little experiment I've done, it seems like containers start up in the order defined in the manifest, even for containers that don't define any dependencies (links, net, etc..):

```
 containers: 
    mysql_db: 
      image: "mysql"
      run: 
        publish: 
          - "3306:3306"
        env: 
          - "MYSQL_USER=admin"
          - "MYSQL_PASSWORD=admin"
          - "MYSQL_ROOT_PASSWORD=rootadmin"
        detach: true
    postgres_db: 
      image: "postgres"
      run: 
        publish: 
          - "5432:5432"
        env: 
          - "POSTGRES_USER=admin"
          - "POSTGRES_PASSWORD=admin"
        detach: true
 groups:
   default: ["mysql_db", "postgres_db"]
 hooks:
   mysql_db:
     post-start: 'sh -c "echo starting mysql... && sleep 5 && echo mysqldb started!"'
   postgres_db:
     post-start: 'sh -c "echo starting postgres... && echo postgres started!"'
```

In this small eg, I've defined postgres and mysql containers, with a post-start hook for mysql that sleeps for 5 seconds and echos some output. There is also a post-start hook defined for the postgres container that immediately echos some output.

My expectation would have been to see "starting postgres..." and "starting mysql..." printed out immediately after performing a ```crane lift``` / ```crane start```. Am I missing something obvious, or are my assumptions about how crane works mistaken?

Cheers
