### ISSUE TITLE
How to use log-opt

### ISSUE THREAD

**Issue by brecke** [michaelsauter/crane#228]
Hi there,

I see that crane supports ``log-opt`` but I can't find a way to make it work. I've looked into the docs but there is no example of that.

I'm interested in adding the ``max-size`` and ``max-file`` attributes to ``docker run``

Thanks!

**Comment by michaelsauter** [comment]
I've never used that option myself, but it should be something like:
```
containers:
  foo:
    run:
      log-opt: ["syslog-address=unix://path", "syslog-facility=daemon"]
```

If that doesn't work, can you post what Crane tries to do when you run it in `--verbose` mode?

**Comment by brecke** [comment]
I'm currently trying this:

```
...
run:
  log-driver: "json-file"
  log-opt: ["max-file=10", "max-size=5m"]
```

But what I get using ``--verbose`` is:

```
docker run --detach --log-driver json-file # missing the log-opt parameter 
```

Am I missing something?
