### ISSUE TITLE
Post-start hooks not always fired

### ISSUE THREAD

**Issue by scornelissen85** [michaelsauter/crane#238]
Sometimes post-start hooks are not fired. I've tested to run a container with Docker 1.9.0 and when I run several times crane run the hook is sometimes fired and sometimes not. For example this yaml:
```
containers:

  test:
    image: centos:7
    run:
      detach: true
      cmd: /bin/sleep 999

hooks:
  test:
    post-start: echo 'hello world'
```
With the command ```crane run test``` executed several times after each other, the hello world is not always fired. Is this some timing issue?

I'm using Docker 1.9.0 with Crane 2.2.0.
