### ISSUE TITLE
Crane v2.5.0 always tries to pull images from registry

### ISSUE THREAD

**Issue by vladejs** [michaelsauter/crane#255]
Even if the image is created locally crane tries to pull it. It happened first with the data container image (`psqldata`) and then with `mypostgres`'s container image. 

This is my configuration:
```
containers:  
  mypostgres:
    image: vladejs/postgres
    run:
      detach: true
      expose: ["5432"]
      publish: ["5432:5432"]
  myapp: 
    image: vladejs/nginx:sf2
    run: 
      volumes-from: ["psqldata"]
      detach: true
      link:
        - mypostgres:postgres
      publish: ["80"]  
  psqldata:  
    image: vladejs/data:pgsql-nginx
    run:
      cmd: "tail -f /dev/null"
      detach: true
```
