### ISSUE TITLE
How to set default container keys?

### ISSUE THREAD

**Issue by dreamcat4** [michaelsauter/crane#273]
Hello.
I need to be always setting certain default keys for each and all containers, when left unspecified. Because there are a bunch of keys which we may commonly set on all containers.

This is a bit like the reverse / counterpart feature of https://github.com/michaelsauter/crane/pull/214

**Comment by dreamcat4** [comment]
Real life example, ripped from my current `crane.yml`: 

```yaml
containers:
  tvh:
    image: dreamcat4/tvheadend:testing
    build:
      context: tvh/testing
    run:
      net: none
      cmd: --satip_xml http://192.168.1.22:8080/desc.xml --bindaddr 192.168.2.3
      log-opt:
        - max-size=10m
        - max-file=2
      volumes-from:
        - tvh.config.id
      env:
        - hts_gid=1616
        - eth0_up=true
        - pipework_wait=eth0
        - pipework_cmd=eth0 -i eth0 @CONTAINER_NAME@ udhcpc 0a:00:00:02:00:03
      detach: true

  nginx.ansible:
    image: dreamcat4/nginx
    run:
      net: none
      log-opt:
        - max-size=10m
        - max-file=2
      env:
        - eth0_up=true
        - pipework_wait=eth0
        - pipework_cmd_eth0=eth0 -i eth0 @CONTAINER_NAME@ udhcpc 0a:00:00:80:00:01
      detach: true
```

As we can see - its a lot of repetition, which is actually repeated many more times (i have 16-19 containers). It is probably the largest part of my crane.yml file. And making it hard to read / navigating. I like concise things, that do not repeat themselves.

Suggestion:

Having a high-level `default:`(`s`) key, under which is a skeleton of the global presets. Example:

```yaml
containers:
  defaults:
    run:
      net: none
      log-opt:
        - max-size=10m
        - max-file=2
      env:
        - eth0_up=true
        - pipework_wait=eth0
      detach: true
```

Or make `defaults:` the toplevel key instead of nesting it withing containers. Whichever way around.

**Comment by dreamcat4** [comment]
The above example might not seem much improvement ^^ for only 2 containers. But if multiply that by an order of magnitude, (12-20+ containers). Then it should result in much more compact the crane file.

So how to do this? Is there an example yet with crane generator?

**Comment by dreamcat4** [comment]
Ah OK. Maybe this can be done with YAML. There is no decent example of it in the Crane README file so I am really guessing here...

Could this work?

```yaml
containers:
  default1: &container-defaults1
    run: &run
      net: none
      log-opt:
        - max-size=10m
        - max-file=2
      env:
        - eth0_up=true
        - pipework_wait=eth0
      detach: true

containers:
  tvh:
    <<: *container-defaults1
    image: dreamcat4/tvheadend:testing
    run:
      cmd: --satip_xml http://192.168.1.22:8080/desc.xml --bindaddr 192.168.2.3
      volumes-from:
        - tvh.config.id
      env:
        - hts_gid=1616
        - pipework_cmd=eth0 -i eth0 @CONTAINER_NAME@ udhcpc 0a:00:00:02:00:03

  nginx.ansible:
    <<: *container-defaults1
    image: dreamcat4/nginx
    run:
      env:
        - pipework_cmd_eth0=eth0 -i eth0 @CONTAINER_NAME@ udhcpc 0a:00:00:80:00:01
```

**Comment by bjaglin** [comment]
Feel free to experiment with YAML features, for us it worked quite well, but there are indeed some limitations. See https://github.com/michaelsauter/crane/issues/52#issuecomment-73783293.

**Comment by bjaglin** [comment]
and remember `env:` supports mapping syntax, which works better for merging

**Comment by dreamcat4** [comment]
Great! It works! With keys merging and everything. I really think some similar example should be added into the documentation somewhere. Or a gist link --> elsewhere / whatever.

Here is an example:

```yaml
containers:

  _defaults: &defaults
    image: busybox
    run:
      net: eth0
      log-opt:
        - max-size=10m
        - max-file=2
      env:
        - eth0_up=true
        - pipework_wait=eth0
      detach: true

  _nginx: &nginx
    <<: *defaults
    image: dreamcat4/nginx

  nginx-irc:
    <<: *nginx
    run:
      ip: 192.168.80.97

  _samba: &samba
    <<: *defaults
    image: dreamcat4/samba
    run:
      memory: 500m
      memory-swap: 600m

  smb.tv:
    <<: *samba
    run:
      hostname: smb-tv
      cmd: -t "Europe/London"
      env:
        - pipework_cmd=eth0 -i eth0 @CONTAINER_NAME@ udhcpc 0a:00:00:03:00:03
```

And the resulting cmdline flags:

```sh
$ crane create -v nginx-irc
--> docker create --env eth0_up=true --env pipework_wait=eth0 --ip 192.168.80.97 --log-opt max-size=10m --log-opt max-file=2 --net eth0 --name nginx-irc dreamcat4/nginx

$ crane create -v smb.tv
--> docker create --env pipework_cmd=eth0 -i eth0 @CONTAINER_NAME@ udhcpc 0a:00:00:03:00:03 --hostname smb-tv --log-opt max-size=10m --log-opt max-file=2 --memory 500m --memory-swap 600m --net eth0 --name smb.tv dreamcat4/samba -t Europe/London
```

**Comment by bjaglin** [comment]
Happy to know it worked for you. Maybe you could open a doc PR with this? Does it mean we can close this particular issue since YAML features are enough?

**Comment by dreamcat4** [comment]
Yes.
There is another problem. I have created as a gist, because is simply too long to bloat the crane README file:

https://gist.github.com/dreamcat4/2dd2673184cf5da0d68b

So I'm not entirely sure how to add that in the existing docs here:

https://github.com/michaelsauter/crane/blob/master/README.md#yaml-advanced-usage

Except only to remove the original example, and replace it with a link to the other page.

**Comment by dreamcat4** [comment]
If Crane could auto-flatten those troublesome lists, if they are nested: [Then we could to this!](http://stackoverflow.com/a/30770740/287510) However that is not yet a feature supported by crane.

So can we do that in crane? So long as the array is meant to be flat and not nested. - then just auto-flatten them? I've looked online and everyone seems to agree that it is the only way around the list-merging problem.

**Comment by michaelsauter** [comment]
@dreamcat4 Thanks for writing this up. Two questions:

* Did you try having those "templates" on the top-level to avoid having so satisfy Crane's parsing?
* If I link to it in the readme, I'd like to host the gist in the repo. Would you be OK with me copying the content into the Crane Wiki, and doing some minor adjustments, and linking to you as the original author?

**Comment by dreamcat4** [comment]
1) No i didnt

2) Yes thats absolutely fine. Please copy gist --> better location. Please also make any corrections you see fit.

**Comment by bjaglin** [comment]
@dreamcat4 as mentioned in https://github.com/michaelsauter/crane/issues/273#issuecomment-194340190, `label` and `env` do support mappings on top of lists, so you might be better off trying out with that syntax

**Comment by dreamcat4** [comment]
Hi @bjaglin can you please give an example of that here? For example what if I wished to convert this env: list to the other syntax?

```yaml
containers:
  container:
    run:
      env:
        - var1=value1
        - var2=value2
        - var3=value3
        - var4=value4
```

**Comment by bjaglin** [comment]
@dreamcat4 there you go:
```
containers:
  container:
    run:
      env:
        var1: value1
        var2: value2
        var3: value3
        var4: value4
```
