### ISSUE TITLE
cant run one specified container when default group defined

### ISSUE THREAD

**Issue by mfrankiewicz** [michaelsauter/crane#285]
When I try to run only one container using `crane run container_name` i get this error:
> ERROR: Command cannot be applied to any container.

but when i remove declaration of default group from .yml file - it works properly.

**Comment by michaelsauter** [comment]
Could you post your config file so I can reproduce? Thanks!

**Comment by mfrankiewicz** [comment]
Sure, here is my config:
```yaml
containers:
    web-ssrs:
        image: wiosna/web-dev
        dockerfile: ../docker-images/web
        run:
            net: wiosna-dev
            ip: "172.19.0.5"
            volume: [".:/var/www"]
            workdir: /var/www
            detach: true
    web_it:
        image: wiosna/web-dev
        dockerfile: ../docker-images/web
        run:
            net: wiosna-dev
            ip: "172.19.0.5"
            volume: [".:/var/www", "/home/vagrant/.ssh:/root/.ssh"]
            workdir: /var/www
            interactive: true
            tty: true
            rm: true
            cmd: ["-c", "bash"]
groups:
    default: ["web-ssrs"]
```
I can't run only **web_it** container. (**crane run web_it** throws this error: **ERROR: Command cannot be applied to any container.**)
