### ISSUE TITLE
Entries in /etc/hosts not beeing set

### ISSUE THREAD

**Issue by NicoCa** [michaelsauter/crane#323]
Hi, 
with these entries in a crane.yml

```
services:
  #gocd-agent
  gocd-agent:
    image: "mtddb/gocd-agent"
    build:
      context: gocd-agent/.
    privileged: true
    hostname: "gocd-agent"
    requires: [gocd-agent-mysql]
    volume: ["~/.composer_docker:/.composer"]
    detach: true
    env: ["COMPOSER_CACHE_DIR=/.composer"]


  gocd-agent-mysql:
    image: "mtddb/mysql"
    build:
      context: mysql/.
    detach: true

```

and the command `crane up --extend gocd-agent` i am able to create and start the desired containers. 
`docker network inspect bridge` tells me that the containers are in the same network, but the /etc/hosts of the gocd-agent container does not contain an entry for the gocd-agent-mysql container.

What am i missing?

Any help would be very much appreciated!
Thanks in advance.
