### ISSUE TITLE
Build context parameter in docker-compose can not be parsed as string

### ISSUE THREAD

**Issue by mre** [michaelsauter/crane#327]
Given the following `Dockerfile`:
```Dockerfile
FROM debian:jessie
```

and this `docker-compose.yml`
```yaml
services:
  app:
    build: .
```

I get an error when I run `crane up`:

```go
ERROR: yaml: unmarshal errors:
  line 3: cannot unmarshal !!str `.` into crane.BuildParameters
```

The above syntax is valid, according to the [official version 2 docker-compose reference](https://docs.docker.com/compose/compose-file/compose-file-v2/).

If I change the `docker-compose.yml` to look like this, it works:

```yaml
services:
  app:
    build:
      context: .
```
