### ISSUE TITLE
Containers defined in docker-compose.yml can't reach each other

### ISSUE THREAD

**Issue by mre** [michaelsauter/crane#328]
If I run `crane up` with the following `docker-compose.yml`, the containers `foo` and `bar` can't reach each other:

```yaml
version: '2'
services:
  foo:
    image: alpine
    command: sleep 999999
  bar:
    image: alpine
    command: sleep 999999
```

```
# crane exec foo ping bar
ping: bad address 'bar'
```

According to the [documentation](https://docs.docker.com/compose/networking/), the behaviour should be as follows:

> By default Compose sets up a single network for your app. Each container for a service joins the default network and is both reachable by other containers on that network, and discoverable by them at a hostname identical to the container name.

**Workaroud**

By adding links between the containers, everything works as expected:

```yaml
version: '2'
services:
  foo:
    image: alpine
    command: sleep 999999
    links:
      - bar
  bar:
    image: alpine
    command: sleep 999999
    links:
      - foo
```

```
# crane exec foo ping bar
PING bar (172.17.0.3): 56 data bytes
64 bytes from 172.17.0.3: seq=0 ttl=64 time=0.116 ms
64 bytes from 172.17.0.3: seq=1 ttl=64 time=0.129 ms
64 bytes from 172.17.0.3: seq=2 ttl=64 time=0.115 ms
```
