### ISSUE TITLE
crane run always creates a tilde directory

### ISSUE THREAD

**Issue by jamescowie** [michaelsauter/crane#333]
For some reason running `crane run app` I always get a tilde "~" directory created in the folder. Latest version of crane, latest version of docker for mac:

```
version: "3"

services:
  app:
    build: 
        context: images/nginx
    ports:
      - 80:8000
    depends_on:
      - db
      - phpfpm
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ./src:/var/www/html:delegated
      - ~/.composer:/var/www/.composer:delegated
      - sockdata:/sock

  phpfpm:
    image: markoshust/magento-php:5.6-fpm
    links:
      - db
    volumes: *appvolumes

  db:
    build:
        context:  images/percona
    ports:
      - 3306:3306
    env_file: 
       - env/db.env
    volumes:
      - dbdata:/var/lib/mysql
      - ./magentodb:/magentodb:delegated

volumes:
  dbdata:
  sockdata:
```

**Comment by michaelsauter** [comment]
Are you using the accelerated mounts at all? I can't see it in this example. If you do, please paste the logs so I can help you.

I assume the tilde directory is created in `/var/www/.composer`? If so, have you tried replacing `~/.composer` with `$HOME/.composer` to see what happens then?

**Comment by jamescowie** [comment]
Ah sorry missed that, I am using AM's config us just:

```
accelerated-mounts:
  app:
    uid: 1000
    gid: 1000
```

I will check the composer line, I think it also happend when I removed that line but I have tried a few things this weekend I lost track.
