### ISSUE TITLE
env vars errors / plugins and multi-config management

### ISSUE THREAD

**Issue by roscopecoltran** [michaelsauter/crane#342]
Hi guys,

Hope you are all well !

# **1. Env errors**

I just found an error while trying to create dynamic image names with crane as it works well with docker-compose. 

**.env:**
```bash
###########################################################
################ Containers Customization #################
###########################################################

### CONSOLE ############################################
GOLANG_BASE_IMAGE_NAME=golang
GOLANG_BASE_IMAGE_TAG=1.11beta3-alpine3.8
GOLANG_BASE_IMAGE=${GOLANG_BASE_IMAGE}:${GOLANG_BASE_IMAGE_TAG}
```

**crane.yml:**
```yaml
services:
  crane:
    image: ${GOLANG_BASE_IMAGE}
    # image: michaelsauter/golang:1.8
    rm: true
    interactive: true
    tty: true
    volume:
    - "$PWD:/go/src/github.com/michaelsauter/crane"
    # volume: ["$GOPATH:/go"]
    workdir: /go/src/github.com/michaelsauter/crane
    share-ssh-socket: true
    cmd: ["/bin/sh"]

commands:
  test: run crane make test
  build: run crane make build
  build-darwin: run crane make build-darwin
  build-darwin-pro: run crane make build-darwin-pro
  gofmt: run crane gofmt -w crane

accelerated-mounts:
  crane:
    uid: 1000
    gid: 1000
```
error:
```bash
crane lift crane
Pulling image  ...
invalid reference format
ERROR: exit status 1
```

Also, I noticed that if I want to create a multi-stage Dockefile and use dynamic base image names, crane is not passing them.

```Dockerfile
####################################
## Builder - image arguments
####################################
ARG BUILDER_ALPINE_VERSION=${BUILDER_ALPINE_VERSION:-"3.7"}
ARG BUILDER_GOLANG_VERSION=${BUILDER_GOLANG_VERSION:-"1.10.3"}
ARG BUILDER_IMAGE_TAG=${BUILDER_IMAGE_TAG:-"${BUILDER_GOLANG_VERSION}-alpine${BUILDER_ALPINE_VERSION}"}
ARG BUILDER_IMAGE_NAME=${BUILDER_IMAGE_NAME:-"golang:${BUILDER_IMAGE_TAG}"}

####################################
## Builder
###################################
FROM ${BUILDER_IMAGE_NAME} AS builder
```

Initially, I spotted these errors while working with laradock (https://github.com/laradock/laradock), and especially with the MySQL container (https://github.com/laradock/laradock/blob/master/mysql/Dockerfile#L1)

# ** Plugins / Composable commands **
I started to extend custom commands as sometimes I have to group them by type and other dynamic stuff but I realized that the best approach would be to have a plugin registry for pluggable and composable macros in my custom commands.  

The idea is to get more scriptable containers and make of crane a tool that simplifies the process of creating reproducible experiments from command-line executions, a frequently-used common denominator in machine learning or advanced local stacks. 

Globally, I just want to import them as golang plugins so no feature creep for other users or myself with the open source/pro version of crane.

Refs:
- https://github.com/matthieudelaro/nut#nut-file-syntax (allows to create macros and managed machine learning containers with GUI)
- https://github.com/m-reda/pipeline (create some custom flows while creating/triggering crane hooks or commands. I will bindata the webui in a this separate plugin)
- https://github.com/aelsabbahy/goss (validate my dockerfiles faster while provisioning or running them)
- https://github.com/qmu/mcc (would allow to create a terminal dashboard to explore crane.yml and trigger some commands, like provisioning a group or checking the logs with tailing the output. I could parse docker-compose.yml or crane.yml file to generate the terminal dashboard/command launcher/ GitHub control panel)

**Note:** But I need to get the final struct loaded by crane after parsing the docker-compose and/or crane file in order to pass correct variables to my plugins.

So it would be awesome to have a plugin registry in crane, with shared contextual data, so we could extend it easily. 

**Go plugins examples:**
- Generic example for golang plugin: https://github.com/vladimirvivien/go-plugin-example/blob/master/greeter.go#L20-L28
- Example for a registry of golang plugins:
   - https://github.com/devopsfaith/krakend/blob/master/plugin/plugin.go
   - https://github.com/devopsfaith/krakend/blob/master/plugin/register.go
   - https://github.com/devopsfaith/krakend/tree/master/plugin/tests (some tests)

# **3. Config files**
Would be awesome if we could use https://github.com/jinzhu/configor with crane so we could maybe provide with a string slice some config files (yaml, json, toml or env variables) in order to import plugin config files without hassles too. I already added it in my private fork of crane so I could split a long docker-compose file like the laradock's one into sub-files per group of services. 

# **4. Accelerated Mounts for Mac**

Mainly, I have already forked crane, and started to modify the code to implement all points above but I just realized that, as a mac user, the accelerated mount was a mandatory feature for me too; that's the only reason why I purchased a crane license... ^^ So either, I spent a couple of 1-2 weeks in order to create my own solution with Unison and solve all the problems above, or I keep using crane because I can extend it for more advanced use and keep merging your latest changes.

So my question(s) is/are double-sided, either there is a way to import accelerated mounts if you are a license owner and merge them with a fork and that's fine, or is it possible to create a registry for external golang plugins and config files in the open source/pro version... 

The env variables errors, it would be nice to fix it in any of crane's version.

While hoping that I was clear enough, let me thank you, in advanced, for your time and replies.

Cheers,
Rosco Pecoltran
