### ISSUE TITLE
`ignore` config not respected for `accelerated-mounts`

### ISSUE THREAD

**Issue by nicholasjhenry** [michaelsauter/crane#343]
I'm having trouble configuring the `ignore` option for `accelerated-mounts`.

Here is a sample of my config:

```yaml
# docker_compose.yaml
  ...
  application:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app

# crane.yml
accelerated-mounts:
  application:
    ".:/app":
      ignore: "Name {.git,_build,deps}"
```

As you can see the `ignore` option is not being translated to the container running unison:

```
PID                 USER                TIME                COMMAND
93272               root                0:00                {sync} /bin/sh /usr/local/bin/sync -auto -batch -ignore='Name {.git}' -contactquietly -confirmbigdel=false -prefer=newer -repeat=watch /bind-mount /data-volume
93327               root                0:00                ash -c unison -auto -batch -ignore='Name {.git}' -contactquietly -confirmbigdel=false -prefer=newer -repeat=watch /bind-mount /data-volume
93328               root                0:05                unison -auto -batch -ignore=Name {.git} -contactquietly -confirmbigdel=false -prefer=newer -repeat=watch /bind-mount /data-volume
93329               root                0:00                /usr/local/bin/unison-fsmonitor
```

What am I missing here?
