### ISSUE TITLE
Nil pointer error when running `crane lift -c deploy/docker-compose.yml`

### ISSUE THREAD

**Issue by nmrshll** [michaelsauter/crane#356]
## Steps to reproduce

1. File at `./deploy/docker-compose.yml`:
```yaml
version: "3.8"
services:
  timescale:
    image: "timescale/timescaledb:1.7.4-pg12"
```
2. Run `crane lift -c deploy/docker-compose.yml` in `./`

The error message is:
```
crane lift --config=./deploy/docker-compose.yml
ERROR: runtime error: invalid memory address or nil pointer dereference
```
