### ISSUE TITLE
Support for referencing groups within group definition in crane.yaml

### ISSUE THREAD

**Issue by bjaglin** [michaelsauter/crane#52]
Rather than writing this:

```
groups:
  fullstack:
    - memcached
    - redis
    - mysql
    - cassandra
    - kestrel

  secondary:
    - memcached
    - redis
  primary:
    - mysql
    - cassandra
    - kestrel
```

... i'd like to be able to write:

```
groups:
  fullstack:
    - secondary
    - primary

  secondary:
    - memcached
    - redis
  primary:
    - mysql
    - cassandra
    - kestrel
```

This is just an example, we now have 16 containers, so this gets quite messy and error-prone when adding new ones.

Implementation-wise, I'd see an extra fallback compared to the current behavior: if one of the value in a group definition is not a container, try looking up if a group of that name exists. That should work no matter in which orders the groups are defined, and bwarf nicely on a cycle.

As usual, just opening that for discussion - I should be able to find some time sooner or later to implement it.

**Comment by dreamcat4** [comment]
@bjaglin Would you mind giving a real-workd example of these YAML dry references? e.g. Re-writing the example you posted at the top of this page? That would be particularly helpful for me, who are unfamiliar with how they work. Didn't think YAML could be so clever as that.

**Comment by bjaglin** [comment]
Unfortunately, YAML anchor/references allow you to merge maps, but not lists, so the example above can't really be improved by using them (my comment was a bit off I guess). We are however using them for other purposes, for example:

```
containers:
  proxy:
    <<: *daemon-defaults
    image: docker-registry.net/proxy:$PROXY_TAG
    run:
      link:
        - mysql-proxy:mysql

  wait-mysql-proxy:
    <<: *interactive-defaults
    image: busybox
    run:
      cmd: ["sh", "-c", "for i in `seq 1 20`; do sleep 1 && echo '' | nc mysql 3306 && exit 0 || echo 'retrying...'; done; exit 1"]
      link:
        - mysql-proxy:mysql

  mysql-proxy:
    <<: *daemon-defaults
    image: docker-registry.net/mysql:$MYSQL_PROXY_TAG

daemon-defaults: &daemon-defaults
  run:
    detach: true
    publish-all: true

interactive-defaults: &interactive-defaults
  run:
    tty: true
    interactive: true
  start:
    attach: true
    interactive: true
```
