### ISSUE TITLE
Opt-in feature: block until exposed ports are bound when starting containers

### ISSUE THREAD

**Issue by bjaglin** [michaelsauter/crane#74]
Proposal
-----------
Allow new container flags `hooks.run-start.pre` &  `hooks.run-start.post` in the config, which are (potentially blocking) shell commands to be executed in the foreground before and after the `docker run` or `docker start`  command for that container. This allow for custom waiting/presence/sidekicking code. Return code from these commands is checked so they can interrupt the flow.

Use-case
-------------
For example, if I want `foo` to be started only if/after the port `1234` of `bar` is bound:
```
containers:
  foo
    image: foo
    run:
      tty: true
      interactive: true
      link:
        - bar:bar
    hooks:
      run-start:
        pre: "docker run -ti --rm --link bar:bar busybox sh -c 'for i in `seq 1 10`; do sleep 1 && nc bar 1234 && exit 0 || echo retrying...; done; exit 1'"

  bar
    image: bar
    run:
      expose:
        - 1234
```

To accomplish this currently, I have to define an extra container in between the producer/server `bar` and consumer/client `foo`, and define a dummy `run.volumse-from` from the consumer/client to that middle container to explicitly declare the dependency.

```
containers:
  foo
    image: foo
    run:
      tty: true
      interactive: true
      link:
        - bar:bar
      volumes-from:
        - wait-for-bar

  wait-for-bar
    image: busybox
    run:
      tty: true
      interactive: true
      cmd: ["sh", "-c", "for i in `seq 1 10`; do sleep 1 && nc bar 1234 && exit 0 || echo retrying...; done; exit 1"]
      link:
        - bar:bar

  bar
    image: bar
    run:
      expose:
        - 1234
```

I think this is a common use case for single-host orchestration, and this is generic enough to cover many use cases.
