### ISSUE TITLE
providing order breaks target functionality

### ISSUE THREAD

**Issue by pczekaj** [michaelsauter/crane#81]
For current version from master if I provide "order" I won't be able to provide target.

crane.yml:

```
containers:
    a:
        dockerfile: a
        image: a

    b:
        dockerfile: b
        image: b

    c:
        dockerfile: c
        image: c

order: ["a", "b", "c"]    

groups:
    default: ["a", "b"]
    g1: ["a"]
    g2: ["b", "c"]
```

result of status option for g1 group (same result for any other group):

```
crane status --target="g1"
NAME    IMAGE   ID      UP TO DATE      IP      PORTS   RUNNING
c       c       -       -               -       -       -
b       b       -       -               -       -       -
a       a       -       -               -       -       -
```

expected result would be to show just one container "a" and it works that way if I comment out "order"
