### ISSUE TITLE
YAML inherited attributes syntax doesn't work

### ISSUE THREAD

**Issue by phuongnd08** [michaelsauter/crane#97]
Since I use a lot of environment variables/links between my container, would love to have attributes being inherited (like this http://stackoverflow.com/questions/14184971/more-complex-inheritance-in-yaml)

I tried this YAML but crane didn't evaluate the yaml with inheritance in mind:

```
containers:
  web:
    image: phuongnd08/rails:web
    dockerfile: .
    run:
      cmd:
        - bundle
        - exec
        - thin
        - "-C"
        - "config/thin.yml"
      env: &env
        - RACK_ENV=production
        - RAILS_ENV=production
        - REDIS_URL=redis://redis:6379/
        - MEMCACHE_SERVERS=memcached
        - POSTGRESQL_HOST=db
      link: &link
        - redis:redis
        - db:db
        - memcached:memcached
      detach: false
  sidekiq:
    image: phuongnd08/rails:web
    dockerfile: .
    run:
      cmd:
        - bundle
        - exec
        - sidekiq
        - "-C"
        - "config/sidekiq.yml"
      env:
        <<: *env
      link:
        <<: *link
      detach: true
```

```
$ crane run -v -c crane/web-server.yml --recreate -t sidekiq
Command will be applied to: sidekiq

Killing container sidekiq ...
--> docker kill sidekiq
sidekiq
Removing container sidekiq ...
--> docker rm sidekiq
sidekiq
Running container sidekiq ...
--> docker run --interactive --tty --name sidekiq phuongnd08/giasu:web bundle exec sidekiq -C config/sidekiq.yml
```

(So no links and environment variables being passed to sidekiq container)
